import DOMPurify from "dompurify";

/** Rich article HTML (e.g. Dev.to): semantic tags + tables/code; XSS handled by DOMPurify. */
const CONFIG: Parameters<typeof DOMPurify.sanitize>[1] = {
  ALLOWED_TAGS: [
    "p",
    "br",
    "hr",
    "div",
    "span",
    "section",
    "article",
    "main",
    "aside",
    "header",
    "footer",
    "nav",
    "strong",
    "em",
    "b",
    "i",
    "u",
    "s",
    "mark",
    "del",
    "ins",
    "sub",
    "sup",
    "small",
    "a",
    "ul",
    "ol",
    "li",
    "dl",
    "dt",
    "dd",
    "blockquote",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "pre",
    "code",
    "img",
    "picture",
    "source",
    "figure",
    "figcaption",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "colgroup",
    "col",
  ],
  /** Keep layout/classes from feeds so prose + sanitization work together */
  ALLOWED_ATTR: [
    "href",
    "title",
    "src",
    "alt",
    "loading",
    "decoding",
    "class",
    "id",
    "width",
    "height",
    "colspan",
    "rowspan",
    "scope",
    "start",
    "type",
    "reversed",
    "cite",
    "datetime",
    "target",
    "rel",
    "media",
    "sizes",
    "srcset",
  ],
  FORBID_TAGS: [
    "iframe",
    "object",
    "embed",
    "form",
    "input",
    "textarea",
    "select",
    "option",
    "button",
    "style",
    "script",
    "link",
    "meta",
    "base",
  ],
  ALLOW_DATA_ATTR: false,
  ALLOW_UNKNOWN_PROTOCOLS: false,
  ADD_ATTR: ["target", "rel"],
};

export function sanitizeArticleHtml(html: string) {
  if (!html) return "";
  return DOMPurify.sanitize(html, CONFIG);
}
